### PR TITLE
VULCAN-101 Create Resource super-interfaces and use them instead of separate ones

### PR DESCRIPTION
**Pull request by ahdezma**

### CODE REVIEW

**Comment by ahdezma** [comment]
Thanks to @csierra for the big help with this PR ;)

**Comment by nhpatt** [comment]
LGTM :) merge?

**Comment by nhpatt** [comment]
ci:test

**Comment by csierra** [comment]
> Thanks to @csierra for the big help with this PR ;)

anda bobo... de nada!

**Pull request merged**
