### PR TITLE
APIO-105 Create BaseRoutesBuilder and simplify routes builders

### PR DESCRIPTION
**Pull request by ahdezma**

### CODE REVIEW

**Comment by ahdezma** [comment]
ci:test

**Comment by JorgeFerrer** [comment]
Is it possible to reuse with composition instead of with inheritance?

Inheritance of "Base" classes, quickly becomes hard to evolve over time.

**Comment by ahdezma** [comment]
@JorgeFerrer What do you mean by "composition" in this case?

**Comment by JorgeFerrer** [comment]
There are many articles explaining different techniques for doing composition over inheritance. There is even a wikipedia entry! https://en.wikipedia.org/wiki/Composition_over_inheritance

I haven't looked into the code of the Base class to be able to tell what's the best approach in this case, but I tend to think there must be a better way than inheriting the functionality from a base class.

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
Thanks for the response @JorgeFerrer I have updated it, at first I mistook what you were saying with [functional function composition](https://en.wikipedia.org/wiki/Function_composition_(computer_science)) >.<

**Pull request merged**
