### PR TITLE
APIO-111 APIO modules should be deployed on Liferay Portal on deployment phase

### PR DESCRIPTION
**Pull request by ahdezma**

### CODE REVIEW

**Comment by ahdezma** [comment]
ci:retest

**Comment by ahdezma** [comment]
cc @pavel-savinov

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
@Ithildir do you know why the tests are failing?

**Comment by Ithildir** [comment]
Hi @ahdezma,
When we run `ant all`, we only compile projects with the `.lfrbuild-portal` marker file. The other ones are not even included in the Gradle build, so, when building `apio-architect-api`, Gradle is unable to find `apio-architect-test`.

If should move the code you need in a `-test-util` module (with the `.lfrbuild-portal` marker file), there are already a few examples in the portal.

**Comment by ahdezma** [comment]
Will do. Thanks @Ithildir !!

**Comment by ahdezma** [comment]
ci:test

**Pull request merged**
