### PR TITLE
APIO-215 As an APIO Architect developer I want representations to be easier to debug

### PR DESCRIPTION
**Pull request by ahdezma**
The current implementation is using GSON for serializing/deserializing JSON.

Although JSON Object is (by specification) unordered...

> An object is an unordered set of name/value pairs. An object begins with { (left brace) and ends with } (right brace). Each name is followed by : (colon) and the name/value pairs are separated by , (comma).}}

...there are some libraries that allow an alphabetical order of these structures, which eases the development and debugging of APIs, as developers can know better where to look.

## Possible solution

GSON (current implementation is based on it) doesn't allow this ordering, but for example, Jackson allows it, by using the [SORT_PROPERTIES_ALPHABETICALLY](https://github.com/FasterXML/jackson-databind/blob/496e591c5b6aef267c671baf3875bf1313e023e7/src/main/java/com/fasterxml/jackson/databind/MapperFeature.java#L262) configuration.

Also using Jackson should also provoke a performance increasing.

### CODE REVIEW

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:test

**Comment by nhpatt** [comment]
I hate u.

**Comment by ahdezma** [comment]
😢

**Pull request merged**
