### PR TITLE
APIO-167 Ease message mapper testing by using snapshot testing

### PR DESCRIPTION
**Pull request by ahdezma**

### CODE REVIEW

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
Hey @jpince! we are getting a weird error that we aren't able to reproduce neither in local nor in travis... can you shed some light over this issue?

**Comment by jpince** [comment]
@shuyangzhou can you please help @ahdezma? ProblemJSONErrorMessageMapperTest.testProblemJSONErrorMessageMapper is failing and he can't reproduce it locally. From the stacktrace, I think it has to do with the jackson implementation in https://github.com/liferay/com-liferay-apio-architect/commit/328f170516e0acec46803eb57cb9d98d82192565.
```
     [echo] com.liferay.apio.architect.error.problem.json.internal.ProblemJSONErrorMessageMapperTest > testProblemJSONErrorMessageMapper FAILED
     [echo]     java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ObjectNode.putRawValue(Ljava/lang/String;Lcom/fasterxml/jackson/databind/util/RawValue;)Lcom/fasterxml/jackson/databind/node/ObjectNode;
     [echo]         at com.liferay.apio.architect.message.json.JSONObjectBuilder$FieldStep.numberValue(JSONObjectBuilder.java:520)
     [echo]         at com.liferay.apio.architect.error.problem.json.internal.ProblemJSONErrorMessageMapper.mapStatusCode(ProblemJSONErrorMessageMapper.java:55)
     [echo]         at com.liferay.apio.architect.writer.ErrorWriter.writeError(ErrorWriter.java:59)
     [echo]         at com.liferay.apio.architect.test.util.json.MessageMapperTesterBuilder$MessageMapperStep.validateErrorMessageMapper(MessageMapperTesterBuilder.java:247)
     [echo]         at com.liferay.apio.architect.error.problem.json.internal.ProblemJSONErrorMessageMapperTest.testProblemJSONErrorMessageMapper(ProblemJSONErrorMessageMapperTest.java:36)
```
[Console](https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(master)/109/console)

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:test

**Pull request closed without merging**
